# Uncomment the next line to define a global platform for your project
 platform :ios, '13.6'

target 'integratedBudget' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for integratedBudget

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Functions'
  
  pod 'Alamofire'
end
